name: LiteCommands CI Build

on:
  push:
    branches: [ master-custom ]
  pull_request:
    branches: [ master-custom ]
jobs:
  build:
    name: "Build with JDK${{ matrix.jdk }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        jdk: [ 8, 11, 17, 21 ]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean test clean build
        env:
          GIT_BRANCH: ${{ github.ref }}
          GIT_COMMIT: ${{ github.sha }}